"""Application-owned audit persistence; graph checkpoints cannot confer authority."""

from typing import Protocol

from procurement_intelligence_lab.platform.semantics.agent_runs import AgentEvent, AgentRun
from procurement_intelligence_lab.platform.semantics.scope import RequestContext


class RunStore(Protocol):
    def create(self, run: AgentRun, initial: AgentEvent, *, context: RequestContext) -> None: ...
    def get(self, run_id: str, *, context: RequestContext) -> AgentRun: ...
    def append(self, event: AgentEvent, *, context: RequestContext) -> None: ...
    def events(self, run_id: str, *, context: RequestContext) -> tuple[AgentEvent, ...]: ...
